abbr --add --global ga "git add"
abbr --add --global gbd "git branch -D"
abbr --add --global gca "git commit -a -m"
abbr --add --global gcm "git commit -m"
abbr --add --global gcob "git checkout -b"
abbr --add --global gco "git checkout"
abbr --add --global gd "git diff"
